" Activate pathogen
execute pathogen#infect()

" enable syntax
syntax on

" enable linenumbers
set number

" backspace support
set backspace=indent,eol,start

" color settings
syntax enable
set background=dark
colorscheme solarized

" highlight cursor
set cursorline
set cursorcolumn

" column limit
set colorcolumn=80

" mouse support
set mouse=a

" airline
set laststatus=2
let g:airline_powerline_fonts = 1

""" restore cursor when re-editing a file
augroup JumpCursorOnEdit
  au!
  autocmd BufReadPost *
    \ if expand(":p:h") !=? $TEMP |
    \   if line("'\"") > 1 && line("'\"") <= line("$") |
    \     let JumpCursorOnEdit_foo = line("'\"") |
    \     let b:doopenfold = 1 |
    \     if (foldlevel(JumpCursorOnEdit_foo) > foldlevel(JumpCursorOnEdit_foo - 1)) |
    \        let JumpCursorOnEdit_foo = JumpCursorOnEdit_foo - 1 |
    \        let b:doopenfold = 2 |
    \     endif |
    \     exe JumpCursorOnEdit_foo |
    \   endif |
    \ endif
  " Need to postpone using "zv" until after reading the modelines.
  autocmd BufWinEnter *
    \ if exists("b:doopenfold") |
    \   exe "normal zv" |
    \   if(b:doopenfold > 1) |
    \       exe  "+".1 |
    \   endif |
    \   unlet b:doopenfold |
    \ endif
augroup END

" undo settings
set undodir=~/.vim/undodir
set undofile
set undolevels=1000
set undoreload=10000

" highlight searches
set hlsearch

" tab and indent settings
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=8
set smarttab
set autoindent

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


" NERDTree config
let g:nerdtree_tabs_open_on_console_startup = 1
let NERDTreeMapOpenInTab = '<ENTER>'

" tab config
nnoremap <C-S-Left>     :tabprevious<CR>
nnoremap <C-S-Right>    :tabnext<CR>
nnoremap <C-t>          :tabnew<CR>
nnoremap <C-n>          :NERDTreeTabsToggle<CR>

" misc key bindings
nnoremap <C-x> :x!<CR>

" specific filetype stuff
autocmd Filetype html setlocal ts=2 sts=2 sw=2
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2

